### ISSUE TITLE
Include category in canonical URL for product pages 

### ISSUE THREAD

**Issue by winkelsdorf** [mklooss/Loewenstark_Seo#10]
I've set 'catalog/seo/product_use_categories' (in German 'Kategoriepfad für Artikel URLs verwenden') in the backend settings.

For some reason magento (using 1.9.1) still defaults to create canonical urls in product pages without the category as part of the url.

E.g.
shop.dev/product.html
instead of
shop.dev/category/product.html

The same applies for links visible in other places of the store (e.g. on the recently viewed sidebar).

Any hints? Probably not related to Loewenstark_Seo, but I tried this extension and hoped it might help/solve the canonical URLs.

Cheers,
Frederik

**Comment by mklooss** [comment]
i dont have time to check this issue.
This is the source for the canonical url in this extension.

https://github.com/mklooss/Loewenstark_Seo/blob/master/app/code/community/Loewenstark/Seo/Model/Observer.php#L145

**Comment by winkelsdorf** [comment]
Ok thank you, I'll have a look at it in the debugger :)
