### ISSUE TITLE
Error after enabled redirect

### ISSUE THREAD

**Issue by Ahalle** [mklooss/Loewenstark_Seo#24]
Flat is enabled. 

Fatal error: Call to undefined method Mage_Catalog_Model_Resource_Category_Flat_Collection::getId() in /home/[....]/public_html/.modman/Loewenstark_Seo/app/code/community/Loewenstark/Seo/Model/Observer.php on line 530

**Comment by mklooss** [comment]
https://github.com/mklooss/Loewenstark_Seo/blob/master/app/code/community/Loewenstark/Seo/Model/Observer.php#L530

**Comment by riker09** [comment]
Oh boy, major fuck up here. My bad. I'm sending a full PR.
